config/routes.rb
Rails.application.routes.draw do
  get '/html', to: 'tests#html'
  post '/html', to: 'tests#submit_html'
  
  get '/form_tag', to: 'tests#form_tag'
  post '/form_tag', to: 'tests#submit_form_tag'
  
  resources :products do
    collection do
      get :edit_multiple
      patch :update_multiple
    end
  end
  
  resources :pizzas

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/pizza.rb
class Pizza < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  
  validates :price, :numericality => true
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
  def index
  end

  def show
  end

  def new
    @pizza = Pizza.new(name: 'pepperoni')
  end

  def edit
    @pizza = Pizza.find 1
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
  
  def edit
    @product = Product.find params[:id]
  end
  
  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to products_url, notice: 'Product was successfully updated.'
    else
      render "edit"
    end
  end
  
  def edit_multiple
    @products = Product.where(id: params[:product_ids])
  end
  
  def update_multiple
    @products = Product.update(params[:products].keys, params[:products].values)
    @products.reject! { |product| product.errors.empty? }
    if @products.empty?
      redirect_to products_path
    else
      render 'edit_multiple'
    end
  end
  
  private
  
  def product_params
    params.require(:product).permit(:name, :price, :discontinued, :category_id)
  end
  
  
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  def html
  end
  
  def submit_html
    @test = params[:test]
  end
  
  def form_tag
  end
  
  def submit_form_tag
    @test = params[:test]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pizza_helper.rb
module PizzaHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FormPrac</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pizzas/edit.html.erb
<%= form_for @pizza do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <%= f.label :slices %>
  <%= f.text_field :slices %><br>

  <%= f.label :description %>
  <%= f.text_area :description %><br>

  <%= f.submit %>
<% end %>

app/views/pizzas/index.html.erb
<h1>Pizza#index</h1>
<p>Find me in app/views/pizza/index.html.erb</p>
<%= link_to "New Pizza", new_pizza_path %>

app/views/pizzas/new.html.erb
<!-- 
  API:
  form_for(record, options, &block)
    create form for creating/updating a model record
    record: string/symbol of object or actual object
      string/sym will look for an @ version of itself and pass that to builder
      sets action, method class and id based record and resource routing
        new object gets action="/object/new" method="post" no class or id
        existing object gets action="/object/id" method="patch" (where patch hack is used*)
          class="edit_object" id="edit_object_id"
    yields a FormBuilder
    options: html: {hash of html opts}, url: {custom url}, namespace: {"id_prefix"}

  FormBuilders help build forms by scoping them to a specific model/name
    form_for gives the builder an object (by name at least) to work with
    all name attrs will go inside a hash of name/model specified and you define keys for it (model[])
    Change value of submit if new or existing
    can call model form helpers on builder to automatically provide object_name and set value

  Model formhelpers
    form helpers that make it easier to work w/ models & can be combined with form builders
    like the *_tag variants but take an object_name and method parameter, nesting method in the object_name hash in params
      text_field(:person, :name) == params[:person][:name] => value (can't handle actual instance. Require name)
      
-->

<%= form_for :pizza, namespace: "the_form" do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <%= f.label :slices %>
  <%= f.text_field :slices %><br>

  <%= f.label :description %>
  <%= f.text_area :description %><br>

  <%= f.submit %>
<% end %>

app/views/pizzas/show.html.erb
<h1>Pizza#show</h1>
<p>Find me in app/views/pizza/show.html.erb</p>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.collection_select :category_id, Category.order("name"), :id, :name %>
  </div>
  <div class="field">
    <%= f.check_box :discontinued %>
    <%= f.label :discontinued %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Edit product</h1>

<%= render 'form' %>

app/views/products/edit_multiple.html.erb
<!--  
  fields_for(record_name, record_object, options, &block)
    Works just like form_for without making the form tag
    can be called by formbuilder to further nest the input name attrs (useful for nested attrs)
    yields a formbuilder object
-->
<%= form_tag update_multiple_products_path, method: :patch do %>
  <% @products.each do |product| %>
<%= fields_for 'products[]', product do |f| %>
      <% if product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
          <ul>
          <% product.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <h2><%= product.name %></h2>
      <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :price %><br />
        <%= f.text_field :price %>
      </div>
      <div class="field">
        <%= f.label :category_id %><br />
        <%= f.collection_select :category_id, Category.order("name"), :id, :name %>
      </div>
      <div class="field">
        <%= f.check_box :discontinued %>
        <%= f.label :discontinued %>
      </div>
    <% end %>
  <% end %>

  <div class="actions">
    <%= submit_tag "Update" %>
  </div>
<% end %>

app/views/products/index.html.erb
<%= form_tag edit_multiple_products_path, method: :get do %>
<table>
  <tr>
    <th></th>
    <th>Name</th>
    <th>Price</th>
    <th>Discontinued</th>
    <th>Category</th>
    <th></th>
  </tr>
  <% @products.each do |product| %>
    <tr>
      <td><%= check_box_tag 'product_ids[]', product.id %></td>
      <td><%= product.name %></td>
      <td><%= product.price %></td>
      <td><%= product.discontinued ? "Yes" : "No" %></td>
      <td><%= product.category.name %></td>
      <td><%= link_to "Edit", edit_product_path(product) %></td>
    </tr>
  <% end %>
</table>

<%= submit_tag "Edit Checked" %>
<% end %>